### ISSUE TITLE
update pre-build wined3d.dll please

### ISSUE THREAD

**Issue by FogLizard** [yegortimoshenko/wined3d.dll#1]
wined3d.dll for Wine 2.2.1 worked with Wine 3.0, but since the last update to Wine 3.1 no longer works and crashes the Wine. This can be fixed by rebuilding Wine 3.1 with this patch. Could you please release ready-to-use prebuild dll for Wine 3.1?

**Comment by yegortimoshenko** [comment]
Nixpkgs currently only has Wine 3.0, so I've built that: https://github.com/yegortimoshenko/wined3d.dll/releases/tag/wine-3.0

Perhaps that would solve the problem. I'll update Wine to 3.1 and build that version.

**Comment by FogLizard** [comment]
Sorry, but the problem is still present same as with 2.2.1 dll. After I swap this 3.0 dll with my 3.1 dll it works as usual. I have uploaded my dll for 3.1 [here](http://rgho.st/7Bc2VQNbL). There is no hurry for me any longer, but it's a coincidence that I've uploaded a working test result on 3.0 to WineHQ wih your workaround and in the next couple of days updated to Wine 3.1 with this issue. That's the price for running Arch, I guess :) You can find some of info on error below, if it's useful:
Unhandled exception: page fault on write access to 0x00000000 in 32-bit code (0x7d90ef06).
Backtrace:
=>0 0x7d90ef06 wined3d_swapchain_decref+0x26(swapchain=<couldn't compute location>) [/tmp/nix-build-wined3d.dll.drv-0/wine-3.0/dlls/wined3d/../../include/winbase.h:2836] in wined3d (0x0033fb48)
  1 0x7d898240 wined3d_device_init_gdi+0xdf(device=<is not available>, swapchain_desc=<is not available>) [/tmp/nix-build-wined3d.dll.drv-0/wine-3.0/dlls/wined3d/device.c:1179] in wined3d (0x0033fba8)
  2 0x7d9b0a11 in ddraw (+0x10a10) (0x0033fc68)
  3 0x7d9b105f in ddraw (+0x1105e) (0x0033fca8)
  4 0x00417d9a in th (+0x17d99) (0x00497548)
0x7d90ef06 wined3d_swapchain_decref+0x26 [/tmp/nix-build-wined3d.dll.drv-0/wine-3.0/dlls/wined3d/../../include/winbase.h:2836] in wined3d: lock xaddl	%eax,0x0(%esi)
Unable to access file '/tmp/nix-build-wined3d.dll.drv-0/wine-3.0/dlls/wined3d/../../include/winbase.h'
System information:
    Wine build: wine-3.1
    Platform: i386 (WOW64)
    Version: Windows 7
    Host system: Linux
    Host version: 4.14.15-1-ARCH

**Comment by mewmew** [comment]
I can confirm that this is happening on Arch Linux with wine 3.1. Was working for me before, but since the 3.1 release it crashes.

**Comment by mewmew** [comment]
@yegortimoshenko Thanks a lot btw for providing this package! It's tremendously useful when modding the game :)

**Comment by FogLizard** [comment]
Now I have wine 3.4 and previously compiled patch for wine 3.1 no longer works as well. They are changing api frequently now or something. Will you be able to upgrade the patch any time soon?

**Comment by yegortimoshenko** [comment]
I've built patched DLL on top of Wine 3.3 (latest version available to me at the moment): https://github.com/yegortimoshenko/wined3d.dll/releases/tag/wine-3.3

**Comment by FogLizard** [comment]
Nope, crashes on 3.4. I'll have to make a pkgbuild with your patch and compile wine once more, I guess. Damn Arch :)

**Comment by yegortimoshenko** [comment]
I can build it for 3.4 when this PR gets accepted: https://github.com/NixOS/nixpkgs/pull/37292

**Comment by yegortimoshenko** [comment]
Try: https://github.com/yegortimoshenko/wined3d.dll/releases/tag/wine-3.5

I am always going to be at least one version behind Arch Linux unless I decide to maintain Wine package in Nixpkgs myself.
