### ISSUE TITLE
Black screen in fullscreen mode on proprietary NVidia drivers

### ISSUE THREAD

**Issue by jcharaoui** [yegortimoshenko/wined3d.dll#2]
The fix works well when I run it with an emulated virtual desktop, but without it (game running fullscreen), the display flickers a lot. I can still navigate the menu and get a game started, but after 30 seconds or so, the screen goes completely blank. I've tried setting the `orm=backbuffer` trick, to no effect. This is on Debian 9, wine 3.0 (backport) and proprietary nvidia drivers.

**Comment by yegortimoshenko** [comment]
Could you try on Noveau?

**Comment by yegortimoshenko** [comment]
Hi, I moved this project over to GitLab: https://gitlab.com/yegortimoshenko/wined3d.dll/issues/2

Now wined3d.dll has an automatic CI artifact pipeline which means you don't have to wait for me to cut new versions (it automatically runs every week on Sunday). Check out new README if you're still interested.
