### ISSUE TITLE
Black screen either in fullscreen or with virtual desktop

### ISSUE THREAD

**Issue by mozo78** [yegortimoshenko/wined3d.dll#4]
Hello, the wined3d.dll doesn't work here. I tried it with latest dll and wine 3.5 but it always gives a black screen, no matter if virtual desktop is being used or not.
Edit:
A manage to start the menu with this gude:
https://forums.linuxmint.com/viewtopic.php?p=1286407&sid=4903063e28b801dc9265e25923ed50a0#p1286407

I now can run the game but it flickers awfully in fulscreen mode. With virtual desktop it runs fine.

**Comment by yegortimoshenko** [comment]
Hi, I moved this project over to GitLab: https://gitlab.com/yegortimoshenko/wined3d.dll/issues/2

Now wined3d.dll has an automatic CI artifact pipeline which means you don't have to wait for me to cut new versions (it automatically runs every week on Sunday). Check out new README if you're still interested.
